# Generated by Django 5.2.9 on 2025-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512, verbose_name='PDF 파일 경로')),
                ('parsed_content', models.TextField(blank=True, verbose_name='텍스트 추출 원본')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='분석 상태')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
    ]
