# Generated by Django 4.2.16 on 2025-12-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file_path',
        ),
        migrations.AddField(
            model_name='resume',
            name='file_name',
            field=models.CharField(default='', max_length=255, verbose_name='파일명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20, verbose_name='분석 상태'),
        ),
    ]
