# Generated by Django 4.2.16 on 2025-12-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='book',
        ),
        migrations.AddField(
            model_name='post',
            name='book_isbn',
            field=models.CharField(blank=True, db_index=True, help_text='관련 도서 ISBN (FK 없음)', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
