# Generated by Django 6.0 on 2025-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(choices=[('서울 캠퍼스', '서울 캠퍼스'), ('대전 캠퍼스', '대전 캠퍼스'), ('광주 캠퍼스', '광주 캠퍼스'), ('구미 캠퍼스', '구미 캠퍼스'), ('부울경 캠퍼스', '부울경 캠퍼스')], default='서울 캠퍼스', max_length=10, verbose_name='캠퍼스'),
            preserve_default=False,
        ),
    ]
