# Generated by Django 4.2.16 on 2025-12-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campus',
        ),
    ]
