# Generated by Django 5.2.9 on 2025-12-19 06:55

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=256)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=512, null=True)),
                ('publisher', models.CharField(max_length=256)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('page_count', models.IntegerField(default=0)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('publisher_description', models.TextField(blank=True, null=True)),
                ('authors_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('raw_toc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TOCChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, help_text='목차 레벨')),
                ('number', models.CharField(blank=True, help_text='목차 순서/번호', max_length=50, null=True)),
                ('chapter_title', models.CharField(max_length=255)),
                ('composite_text', models.TextField(help_text='RAG 검색용 텍스트')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                'db_table': 'toc_chunks',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', to_field='isbn')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
