# Generated by Django 5.2.9 on 2025-12-19 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tocchunk',
            name='book',
            field=models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book', to_field='isbn'),
        ),
    ]
