# Generated by Django 5.2.9 on 2025-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
