# Generated by Django 4.2.16 on 2025-12-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_review_book_review_isbn_review_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
