# Generated by Django 5.2.9 on 2025-12-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, unique=True, verbose_name='채용공고 URL')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='스크래핑된 본문')),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
    ]
