# Generated by Django 5.2.9 on 2025-12-19 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_extracted_skills', models.JSONField(default=list, verbose_name='보유 기술 목록')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='분석된 회사명')),
                ('jd_required_skills', models.JSONField(default=list, verbose_name='JD 요구 기술 목록')),
                ('jd_main_tasks', models.JSONField(default=list, verbose_name='주요 업무 목록')),
                ('score', models.IntegerField(default=0, verbose_name='적합도 점수')),
                ('reasoning', models.TextField(blank=True, verbose_name='분석 결과 및 근거')),
                ('gap_missing_skills', models.JSONField(default=list, verbose_name='부족한 기술 목록')),
                ('gap_missing_chapters', models.JSONField(default=list, verbose_name='추천 학습 챕터 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
            ],
            options={
                'db_table': 'analysis_results',
            },
        ),
    ]
