# Generated by Django 4.2.16 on 2025-12-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
        ('analysis', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume'),
        ),
    ]
