# Generated by Django 4.2.16 on 2025-12-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_analysisresult_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='rag_recommendations',
            field=models.JSONField(blank=True, default=list, verbose_name='RAG 추천 도서 목록'),
        ),
    ]
